const LOGOUT = "LOGOUT"
const TOKEN = "TOKEN"
const ME = "ME"
const ME_UPDATE_SHIPPINGADDRESS = "ME_UPDATE_SHIPPINGADDRESS"
const ME_UPDATE_AVATAR = "ME_UPDATE_AVATAR"
const ME_UPDATE = "ME_UPDATE"
const ISAUTH = "ISAUTH"

export {
    LOGOUT , TOKEN , ME , ISAUTH , ME_UPDATE_SHIPPINGADDRESS , ME_UPDATE , ME_UPDATE_AVATAR
}