const GET_MAIN_CATEGORIES = "GET_MAIN_CATEGORIES" ;
const GET_SUB_CATEGORIES = "GET_SUB_CATEGORIES" ;
const GET_CATEGORY = "GET_CATEGORY" ;
const CREATE_MAIN_CATEGORY = "CREATE_MAIN_CATEGORY" ;
const COUNT_MAIN_CATEGORY = "COUNT_MAIN_CATEGORY" ;
const COUNT_SUB_CATEGORY = "COUNT_SUB_CATEGORY" ;
const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY" ;
const DELETE_SUB_CATEGORY = "DELETE_SUB_CATEGORY" ;
const EDIT_SUB_CATEGORY = "EDIT_SUB_CATEGORY" ;
const DELETE_MAIN_CATEGORY = "DELETE_MAIN_CATEGORY" ;
const EDIT_MAIN_CATEGORY = "EDIT_MAIN_CATEGORY" ;
const DUPLICATE_MAIN_CATEGORY = "DUPLICATE_MAIN_CATEGORY" ;
const DUPLICATE_SUB_CATEGORY = "DUPLICATE_SUB_CATEGORY" ;
const GET_SUB_CATEGORIES_PARENTS = "GET_SUB_CATEGORIES_PARENTS" ;

export {
    GET_MAIN_CATEGORIES , GET_SUB_CATEGORIES , CREATE_MAIN_CATEGORY ,
    CREATE_SUB_CATEGORY , DELETE_MAIN_CATEGORY , DELETE_SUB_CATEGORY , 
    EDIT_SUB_CATEGORY , EDIT_MAIN_CATEGORY , DUPLICATE_MAIN_CATEGORY , 
    DUPLICATE_SUB_CATEGORY , GET_CATEGORY , COUNT_SUB_CATEGORY , COUNT_MAIN_CATEGORY ,
    GET_SUB_CATEGORIES_PARENTS
}
