const GET_MAIN = "GET_MAIN"
const GET_SINGLE_MAIN = "GET_SINGLE_MAIN"
const DUPLICATE_MAIN = "DUPLICATE_MAIN"
const EDIT_MAIN = "EDIT_MAIN"
const DELETE_MAIN = "DELETE_MAIN"
const GET_COUNT_MAIN = "GET_COUNT_MAIN"
const CREATE_MAIN = "CREATE_MAIN"

export {
    GET_MAIN , GET_COUNT_MAIN , GET_SINGLE_MAIN , DUPLICATE_MAIN , CREATE_MAIN , DELETE_MAIN , EDIT_MAIN
}  