const GET_ORDERS = "GET_ORDERS"
const GET_ORDER = "GET_ORDER"
const COUNT_ORDERS = "COUNT_ORDERS"
const STATUS_ORDERS = "STATUS_ORDERS"



export {
    GET_ORDERS , GET_ORDER , COUNT_ORDERS , STATUS_ORDERS
}