const GET_PRODUCTS = "GET_PRODUCTS" ;
const GET_SINGLE_PRODUCTS = "GET_SINGLE_PRODUCTS" ;
const GET_PRODUCTS_COUNT = "GET_PRODUCTS_COUNT" ;
const DELETE_PRODUCT = "DELETE_PRODUCT" ;
const DUPLICATE_PRODUCT = "DUPLICATE_PRODUCT" ;
const EDIT_PRODUCT = "EDIT_PRODUCT" ;
const CRAETE_PRODUCT = "CRAETE_PRODUCT" ;

 

export {
    GET_PRODUCTS , GET_SINGLE_PRODUCTS  , GET_PRODUCTS_COUNT , EDIT_PRODUCT , DELETE_PRODUCT , DUPLICATE_PRODUCT , CRAETE_PRODUCT
}