const GET_USERS = "GET_USERS"; 
const GET_USER = "GET_USER"; 
const DELETE_USER = "DELETE_USER";
const UPDATE_USER = "UPDATE_USER";
const EDIT_USER = "EDIT_USER";
const EDIT_RULE = "EDIT_RULE";
const ADD_USER = "ADD_USER";
const UPDATE_USER_SUSPENDED="UPDATE_USER_SUSPENDED"
const VERIFIED_USER="VERIFIED_USER"
const COUNT_USER = "COUNT_USER"
export { GET_USERS,GET_USER, DELETE_USER,COUNT_USER, UPDATE_USER, EDIT_USER,ADD_USER ,UPDATE_USER_SUSPENDED,VERIFIED_USER , EDIT_RULE};